-- Esteban pidio explicitamente investigar A FONDO antes de publicar (correccion sobre la 0075,
-- que ya se habia publicado con datos mas superficiales). Esta actualiza summary/comment con lo
-- que la investigacion mas profunda encontro: ilustrador principal, tecnica, influencias
-- artisticas, idiomas, fechas exactas de la campana y ediciones. La pagina inmersiva grande que
-- pidio (parallax, pantalla completa, acceso "secreto" desde la portada en /biblioteca) se
-- construye despues, una vez que termine de mandar las fotos de las ilustraciones interiores --
-- el pidio esperar antes de construirla.
UPDATE books SET
  summary = 'Enciclopedia ilustrada de 410 páginas y más de 700 ilustraciones originales, organizada en 23 capítulos que van desde habilidades básicas de supervivencia (hacer fuego, purificar agua) hasta logros civilizatorios complejos (navegación, aviación, medicina, psicoterapia, música, organización social) — literalmente un manual para reconstruir la civilización desde cero. La estética retrofuturista, con ilustraciones que imitan grabados renacentistas, está inspirada en el enigmático Manuscrito Voynich (siglo XV) y organiza el conocimiento según un sistema de clasificación inspirado en la "Summa Technologiae" de Stanisław Lem. El ilustrador principal, Lev Kaplan (nacido en Ucrania en 1967, radicado en Stuttgart, Alemania, y profesor de ilustración y acuarela en la galería Kunstfabrik de Viena), lideró al equipo de artistas y dibujó buena parte de las piezas él mismo: boceto a lápiz, luego plumilla y tinta acrílica, acuarela, gouache y marcadores, todo sobre papel de acuarela 100% algodón — entre uno y cuatro días por ilustración. Sus influencias declaradas: los maestros del Renacimiento nórdico (Brueghel el Viejo, Durero, Jan van Eyck), la Secesión vienesa (Klimt, Schiele) y los ilustradores de la Edad de Oro estadounidense (Norman Rockwell, J. C. Leyendecker). El equipo escondió a propósito guiños y "huevos de pascua" visuales por todo el libro — referencias a Dalí, a películas — para premiar una segunda mirada.',
  comment = 'Nació de una campaña de Kickstarter/Indiegogo (1 dic 2020 – 5 ene 2021) del colectivo Hungry Minds (fundadores: Vsevolod "Seva" Batichev y Timur Kadyrov, con Artur Stelmakh como socio de crowdfunding) — recaudó más de 3 millones de dólares entre ambas plataformas, el 3er proyecto editorial más financiado en la historia de Kickstarter hasta ese momento. La edición original en inglés se entregó en 2022; existen además ediciones en alemán, español, italiano, francés y japonés (6 idiomas en total), y una edición especial "Gift Box" en caja. La edición española que tiene Esteban la distribuye Duomo Ediciones (3 nov 2025) además del canal directo de Hungry Minds. Precio de tienda oficial: $119.00 USD (~$2,016 MXN al tipo de cambio del 24 ago 2026) -- pendiente confirmar el precio real pagado en Amazon.com.mx. Pesa unos 2.3 kg. Pendiente: página inmersiva propia con las ilustraciones interiores que Esteban está mandando por separado.'
WHERE id = 91;
